---
- hosts: all
  become: yes
  tasks:
  - name: update
    apt: 
      update_cache: yes
      cache_valid_time: 1200
      upgrade: dist
    when:
      ansible_distribution == 'Debian'
      or
      ansible_distribution == 'Ubuntu'
  - name: upgrade all packages
    yum: >
      update_cache: yes
      name: *
      update_cache: yes
    when:
      ansible_distribution == 'Centos'
      or
      ansible_distribution == 'RedHat'
  - name: Install tomcat
    package:
      name: "{{ package }}"
    notify:
      - restart tomcat
  - name: change default settings
    template:
      src: tomcat7.j2
      dest: /etc/default/tomcat7
    notify:
      - restart tomcat
  - name: Install additional package
    package:
      name: "{{ item }}"
    with_items:
      "{{ additional_packages}}"
  - name: configure user management
    template:
      src: tomcat-users.xml.j2
      dest: /etc/tomcat7/tomcat-users.xml
    notify:
      - restart tomcat
  - handlers:
      - name: restart tomcat
        service:
          name: "{{ package }}"
          state: restarted    

