---
- hosts: all
  become: yes
  tasks:
    - name: upgrade all packages
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
    - name: update
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=dist
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
    - name: "{{ tomcat_version }}"
      state: present
      enabled: yes
      notify:
        - restart tomcat
    - name: changing the port value
      template:
        src: server.j2
        dest: /opt/apache-tomcat-8.5.34/conf
      
      